services:
    Bigoen\RedisBundle\Command\RedisFlushCommand:
        arguments:
            $clientHelper: '@bigoen_redis.client_helper'
        tags:
            - { name: 'console.command' }

    Bigoen\RedisBundle\Utils\RedisClientHelper:
        arguments:
            $parameterBag: '@parameter_bag'

    bigoen_redis.client_helper:
        alias: Bigoen\RedisBundle\Utils\RedisClientHelper

